### ISSUE TITLE
Do not provide the test-helper feature

### ISSUE THREAD

**Issue by tarsius** [nlamirault/cerbere#5]
"test-helper.el" isn't a library intended to be loaded with `require`.
Instead it is loaded with `load` by `ert-runner` itself.  Because of
that, it is confusing to provide a feature using `provide`.  It also
isn't possible to use `require` to load `test-helper` because that
might, depending on the order of `load-path` load the "test-helper.el"
of another package that used `ert-runner`.

This is also discussed at rejeep/ert-runner.el#38.

**Comment by tarsius** [comment]
Friendly ping!

**Comment by tarsius** [comment]
Plong?

**Comment by nlamirault** [comment]
See: https://github.com/nlamirault/cerbere/commit/c667c165d9c1657f13d2d46f09ba21b61f9402cc

**Comment by tarsius** [comment]
Thanks!
